### ISSUE TITLE
myinnos.androidscratchcard.ScratchCard.onSizeChanged

### ISSUE THREAD

**Issue by Anu07** [myinnos/AndroidScratchCard#5]
java.lang.IllegalArgumentException: width and height must be > 0

Fatal Exception: java.lang.IllegalArgumentException: width and height must be > 0
       at android.graphics.Bitmap.createBitmap(Bitmap.java:1150)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:1117)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:1067)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:1028)
       at in.myinnos.androidscratchcard.ScratchCard.onSizeChanged(ScratchCard.java:74)
       at android.view.View.sizeChange(View.java:24682)
       at android.view.View.setFrame(View.java:24615)
       at android.view.View.layout(View.java:24472)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
       at android.view.View.layout(View.java:24475)
       at android.view.ViewGroup.layout(ViewGroup.java:7383)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
       at android.view.View.layout(View.java:24475)
       at android.view.ViewGroup.layout(ViewGroup.java:7383)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:24475)
       at android.view.ViewGroup.layout(ViewGroup.java:7383)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:24475)
       at android.view.ViewGroup.layout(ViewGroup.java:7383)
       at com.android.internal.widget.AlertDialogLayout.setChildFrame(AlertDialogLayout.java:358)
       at com.android.internal.widget.AlertDialogLayout.onLayout(AlertDialogLayout.java:351)
       at android.view.View.layout(View.java:24475)
       at android.view.ViewGroup.layout(ViewGroup.java:7383)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:24475)
       at android.view.ViewGroup.layout(ViewGroup.java:7383)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:24475)
       at android.view.ViewGroup.layout(ViewGroup.java:7383)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:1225)
       at android.view.View.layout(View.java:24475)
       at android.view.ViewGroup.layout(ViewGroup.java:7383)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4273)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3708)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2631)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9978)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
       at android.view.Choreographer.doCallbacks(Choreographer.java:809)
       at android.view.Choreographer.doFrame(Choreographer.java:744)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8506)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by myinnos** [comment]
@Anu07 can you share more info when this issue is occurring?
